version: '3.4'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookify-idp:
      image: quay.io/keycloak/keycloak:latest
      container_name: Bookify.Identity
      command: start-dev --import-realm
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      volumes:
        - ./.containers/identity:/opt/keycloak/data
        - type: bind
          source: ./.files/bookify-realm-export.json
          target: /opt/keycloak/data/import/realm.json
        - ./data/transaction-logs:/opt/keycloak/data/transaction-logs
        - ./data/h2:/opt/keycloak/data/h2
      ports:
        - 18080:8080

  bookify-seq:
    image: datalust/seq:latest
    container_name: Bookify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  bookify-redis:
    image: redis:latest
    container_name: Bookify.Redis
    restart: always
    ports:
      - '6379:6379'
